# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Users/markbarbaric/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-2/211.7628.27/CLion.app/Contents/bin/cmake/mac/bin/cmake"

# The command to remove a file.
RM = "/Users/markbarbaric/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-2/211.7628.27/CLion.app/Contents/bin/cmake/mac/bin/cmake" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/markbarbaric/Documents/Developer/C++/Software_Architecture_With_CPP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/markbarbaric/Documents/Developer/C++/Software_Architecture_With_CPP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	"/Users/markbarbaric/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-2/211.7628.27/CLion.app/Contents/bin/cmake/mac/bin/cmake" -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Users/markbarbaric/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-2/211.7628.27/CLion.app/Contents/bin/cmake/mac/bin/cmake" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/markbarbaric/Documents/Developer/C++/Software_Architecture_With_CPP/CMakeFiles /Users/markbarbaric/Documents/Developer/C++/Software_Architecture_With_CPP//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/markbarbaric/Documents/Developer/C++/Software_Architecture_With_CPP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Software_Architecture_With_CPP

# Build rule for target.
Software_Architecture_With_CPP: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Software_Architecture_With_CPP
.PHONY : Software_Architecture_With_CPP

# fast build rule for target.
Software_Architecture_With_CPP/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Software_Architecture_With_CPP.dir/build.make CMakeFiles/Software_Architecture_With_CPP.dir/build
.PHONY : Software_Architecture_With_CPP/fast

#=============================================================================
# Target rules for targets named CPP_GuideLines

# Build rule for target.
CPP_GuideLines: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CPP_GuideLines
.PHONY : CPP_GuideLines

# fast build rule for target.
CPP_GuideLines/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPP_GuideLines.dir/build.make CMakeFiles/CPP_GuideLines.dir/build
.PHONY : CPP_GuideLines/fast

#=============================================================================
# Target rules for targets named SOLID

# Build rule for target.
SOLID: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SOLID
.PHONY : SOLID

# fast build rule for target.
SOLID/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOLID.dir/build.make CMakeFiles/SOLID.dir/build
.PHONY : SOLID/fast

#=============================================================================
# Target rules for targets named DesignPatterns

# Build rule for target.
DesignPatterns: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DesignPatterns
.PHONY : DesignPatterns

# fast build rule for target.
DesignPatterns/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesignPatterns.dir/build.make CMakeFiles/DesignPatterns.dir/build
.PHONY : DesignPatterns/fast

CPP_GuideLines/RunCPPGuideLines.o: CPP_GuideLines/RunCPPGuideLines.cpp.o

.PHONY : CPP_GuideLines/RunCPPGuideLines.o

# target to build an object file
CPP_GuideLines/RunCPPGuideLines.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPP_GuideLines.dir/build.make CMakeFiles/CPP_GuideLines.dir/CPP_GuideLines/RunCPPGuideLines.cpp.o
.PHONY : CPP_GuideLines/RunCPPGuideLines.cpp.o

CPP_GuideLines/RunCPPGuideLines.i: CPP_GuideLines/RunCPPGuideLines.cpp.i

.PHONY : CPP_GuideLines/RunCPPGuideLines.i

# target to preprocess a source file
CPP_GuideLines/RunCPPGuideLines.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPP_GuideLines.dir/build.make CMakeFiles/CPP_GuideLines.dir/CPP_GuideLines/RunCPPGuideLines.cpp.i
.PHONY : CPP_GuideLines/RunCPPGuideLines.cpp.i

CPP_GuideLines/RunCPPGuideLines.s: CPP_GuideLines/RunCPPGuideLines.cpp.s

.PHONY : CPP_GuideLines/RunCPPGuideLines.s

# target to generate assembly for a file
CPP_GuideLines/RunCPPGuideLines.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CPP_GuideLines.dir/build.make CMakeFiles/CPP_GuideLines.dir/CPP_GuideLines/RunCPPGuideLines.cpp.s
.PHONY : CPP_GuideLines/RunCPPGuideLines.cpp.s

Chapter1/SOLID/RunSOLIDExamples.o: Chapter1/SOLID/RunSOLIDExamples.cpp.o

.PHONY : Chapter1/SOLID/RunSOLIDExamples.o

# target to build an object file
Chapter1/SOLID/RunSOLIDExamples.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOLID.dir/build.make CMakeFiles/SOLID.dir/Chapter1/SOLID/RunSOLIDExamples.cpp.o
.PHONY : Chapter1/SOLID/RunSOLIDExamples.cpp.o

Chapter1/SOLID/RunSOLIDExamples.i: Chapter1/SOLID/RunSOLIDExamples.cpp.i

.PHONY : Chapter1/SOLID/RunSOLIDExamples.i

# target to preprocess a source file
Chapter1/SOLID/RunSOLIDExamples.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOLID.dir/build.make CMakeFiles/SOLID.dir/Chapter1/SOLID/RunSOLIDExamples.cpp.i
.PHONY : Chapter1/SOLID/RunSOLIDExamples.cpp.i

Chapter1/SOLID/RunSOLIDExamples.s: Chapter1/SOLID/RunSOLIDExamples.cpp.s

.PHONY : Chapter1/SOLID/RunSOLIDExamples.s

# target to generate assembly for a file
Chapter1/SOLID/RunSOLIDExamples.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOLID.dir/build.make CMakeFiles/SOLID.dir/Chapter1/SOLID/RunSOLIDExamples.cpp.s
.PHONY : Chapter1/SOLID/RunSOLIDExamples.cpp.s

DesignPatterns/Creational/RunCreationalPatterns.o: DesignPatterns/Creational/RunCreationalPatterns.cpp.o

.PHONY : DesignPatterns/Creational/RunCreationalPatterns.o

# target to build an object file
DesignPatterns/Creational/RunCreationalPatterns.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesignPatterns.dir/build.make CMakeFiles/DesignPatterns.dir/DesignPatterns/Creational/RunCreationalPatterns.cpp.o
.PHONY : DesignPatterns/Creational/RunCreationalPatterns.cpp.o

DesignPatterns/Creational/RunCreationalPatterns.i: DesignPatterns/Creational/RunCreationalPatterns.cpp.i

.PHONY : DesignPatterns/Creational/RunCreationalPatterns.i

# target to preprocess a source file
DesignPatterns/Creational/RunCreationalPatterns.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesignPatterns.dir/build.make CMakeFiles/DesignPatterns.dir/DesignPatterns/Creational/RunCreationalPatterns.cpp.i
.PHONY : DesignPatterns/Creational/RunCreationalPatterns.cpp.i

DesignPatterns/Creational/RunCreationalPatterns.s: DesignPatterns/Creational/RunCreationalPatterns.cpp.s

.PHONY : DesignPatterns/Creational/RunCreationalPatterns.s

# target to generate assembly for a file
DesignPatterns/Creational/RunCreationalPatterns.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DesignPatterns.dir/build.make CMakeFiles/DesignPatterns.dir/DesignPatterns/Creational/RunCreationalPatterns.cpp.s
.PHONY : DesignPatterns/Creational/RunCreationalPatterns.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Software_Architecture_With_CPP.dir/build.make CMakeFiles/Software_Architecture_With_CPP.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Software_Architecture_With_CPP.dir/build.make CMakeFiles/Software_Architecture_With_CPP.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Software_Architecture_With_CPP.dir/build.make CMakeFiles/Software_Architecture_With_CPP.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CPP_GuideLines"
	@echo "... DesignPatterns"
	@echo "... SOLID"
	@echo "... Software_Architecture_With_CPP"
	@echo "... CPP_GuideLines/RunCPPGuideLines.o"
	@echo "... CPP_GuideLines/RunCPPGuideLines.i"
	@echo "... CPP_GuideLines/RunCPPGuideLines.s"
	@echo "... Chapter1/SOLID/RunSOLIDExamples.o"
	@echo "... Chapter1/SOLID/RunSOLIDExamples.i"
	@echo "... Chapter1/SOLID/RunSOLIDExamples.s"
	@echo "... DesignPatterns/Creational/RunCreationalPatterns.o"
	@echo "... DesignPatterns/Creational/RunCreationalPatterns.i"
	@echo "... DesignPatterns/Creational/RunCreationalPatterns.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

